CREATE DATABASE IF NOT EXISTS rh_tech;
USE rh_tech;

CREATE TABLE IF NOT EXISTS cargos(
id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(100),
descricao VARCHAR(225)
);

CREATE TABLE IF NOT EXISTS funcionarios(
id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(100) NOT NULL,
cep CHAR(8) NOT NULL,
endereco VARCHAR(50) NOT NULL,
numero INT NOT NULL,
bairro VARCHAR(50) NOT NULL,
cidade VARCHAR(50) NOT NULL,
estado VARCHAR(50) NOT NULL
);

select * from funcionarios;